### ISSUE TITLE
Uninstantiated User variable when not logged in (several locations in codebase)

### ISSUE THREAD

**Issue by wouterbeek** [ClioPatria/ClioPatria#12]
At several points in the codebase logged_on/2 is called with both arguments uninstantiated while the specification is `(-,+)`. When not logged in, each of these calls leaves variable `User` uninstantiated (which is probably unintentional) and causes the predicate to fail later on.

#### Example

[This line](https://github.com/ClioPatria/ClioPatria/blob/master/applications/browse.pl#L541) gives the following error:

```prolog
?- ERROR: [Thread 10] Failed to translate to HTML: \li_persistent_graph(graph_name:'')
```

**Comment by JanWielemaker** [comment]
The failure is intended, but a bit inelegant.  li_persistent_graph(graph_name//1 needs a default
clause.  Fixed in 2516cea90c1dac80194456f8afdec395dda0704d
