### ISSUE TITLE
Operator @/1 not always defined (requires XPCE)

### ISSUE THREAD

**Issue by rla** [ClioPatria/ClioPatria#16]
Operator @/1 is not always defined. This causes syntax error:

    sparql_runtime.pl:1241:14: Syntax error: Operator expected

Could not be easily fixed as XPCE is required for regex support? Reference to code:

https://github.com/ClioPatria/ClioPatria/blob/master/rdfql/sparql_runtime.pl#L1241

I got this error while trying to run ClioPatria inside mndrix' SWI-s base Docker image https://hub.docker.com/r/mndrix/swipl/ which seems to lack GUI packages.

**Comment by JanWielemaker** [comment]
Changed to @(arg1).  This of course does not avoid the runtime error if you actually use SPARQL queries that depend on this.

What we really need is regex in SWI-Prolog itself, i.e., without xpce.  That would also significantly speedup regex matching, in particular on rather short literals.

**Comment by rla** [comment]
I would like to reopen. Only the first operator usage is fixed, `@arg2` is still in the code:
https://github.com/ClioPatria/ClioPatria/commit/68a35c31147b315a1a234f33d17ed919caaeb41f

**Comment by JanWielemaker** [comment]
Sorry ...  Should be fixed now.  At least I can't find any other `@arg` ...

**Comment by rla** [comment]
Thank you! Just upgraded and it's running fine.
