### ISSUE TITLE
Better approach towards throwing HTTP errors

### ISSUE THREAD

**Issue by wouterbeek** [ClioPatria/ClioPatria#21]
For many unanticipated request types ClioPatria currently returns a 500 status code.
Is there a better approach towards returning 4xx errors?

**Comment by wouterbeek** [comment]
`library(http/http_exceptions)` may need some additions for this to work.

**Comment by JanWielemaker** [comment]
I think this discussion needs to be at SWI-Prolog/packages-http.  Still, it is hard.  User code can succeed (ok) or throw a http-aware exception (nicely mapped).  That is all fine.  It may also fail or throw any other exception.  This can mean anything.  Sometimes it means the handler didn't check the request properly and fails further down the line.   In most cases it means the handler is broken.

**Comment by wouterbeek** [comment]
Moved over to `library(http)`: [https://github.com/SWI-Prolog/packages-http/issues](https://github.com/SWI-Prolog/packages-http/issues)
