### ISSUE TITLE
Support for HTTP methods other than GET and POST

### ISSUE THREAD

**Issue by wouterbeek** [ClioPatria/ClioPatria#22]
E.g., sending an OPTIONS or HEAD request now returns an HTTP 500 status code.

**Comment by wouterbeek** [comment]
We should at least send 501 (Unimplemented)?

**Comment by JanWielemaker** [comment]
This too should be at SWI-Prolog/packages-http.git.  Would be nice.  The proper way out is probably to extend the http_handler/3 registration.  That also might allow us to reply to OPTIONS and HEAD in a generic way.  Probably something like adding `methods(ListOfMethods)`, where the default is `methods([get])`.

**Comment by wouterbeek** [comment]
Moved to `library(http)`: [https://github.com/SWI-Prolog/packages-http/issues/20](https://github.com/SWI-Prolog/packages-http/issues/20)
