### ISSUE TITLE
Use `rdf11` i.o. `rdf_db`

### ISSUE THREAD

**Issue by wouterbeek** [ClioPatria/ClioPatria#33]
This depends a bit on where `rdf11` will be placed.  Will it be under `library(semweb/rdf11)`?

**Comment by JanWielemaker** [comment]
library(semweb/rdf11) seems the most sensible.  What about including rdf_collections in rdf11 and
adding two libs to semweb: rdf11 and rdf11_containers?

**Comment by jrvosse** [comment]
Can I already get a sneak preview of rdf11?  I cannot find a related branch in the semweb package ...

**Comment by JanWielemaker** [comment]
At https://github.com/JanWielemaker/rdf11

Once we are happy (getting there), rdf11.pl will move to the semweb package.
