### ISSUE TITLE
Rewrite win-config into something that could be easily run on Windows

### ISSUE THREAD

**Issue by berezovskyi** [ClioPatria/ClioPatria#52]
I had to help my friend yesterday with the installation of ClioPatria on Windows and it didn't work.

First, running `..\cliopatria\configure` under *cmd* failed because it was a bash script.

Next, running `../cliopatria/configure` or `SWIPL=swipl ../cliopatria/configure` under *git bash* caused the execution to hang (no excessive CPU use).

Finally, I ran the command from the `configure` script by hand:

    swipl -f ../cliopatria/setup.pl --

And I got an error (didn't save the exact message, sorry) like "setup/5 is not defined".

What finally worked (after a sneak peek into `win-config.c`) was this:

    swipl-win.exe -s ../cliopatria/setup.pl

The problem with `win-config.c` is that you need a compiler to run it and it comes with a Makefile (how ironic) so I would have had to set up full gcc/make toolchain under Windows using cygwin.

Three ideas:

* add `configure.bat` that would mimic `configure` for bash but look for `swipl-win.exe` instead (IMO the easiest solution, but I still have no idea why the non-GUI `swipl` didn't work).
* rewrite `win-config.c` into Prolog (I am just learning it so would need some help if I do a PR). I found http://www.swi-prolog.org/pldoc/man?section=registry but maybe it's an overkill.
* rewrite `win-config.c` into Python (it's installed on almost every dev machine and easy to peek at).

I would actually recommend replacing `configure` with `bin/clio` but let's take it in #51

**Comment by JanWielemaker** [comment]
At least the (AFAIK documented) theory is that you run `win-config.exe` from the toplevel directory.  That is the compiled version of `win-config.c`.   This always worked for the only colleague I know that uses ClioPatria on Windows.

**Comment by berezovskyi** [comment]
Oh, snap, I totally missed that binary!

**Comment by berezovskyi** [comment]
I use a mac, so can't test it now.

**Comment by berezovskyi** [comment]
Confirmed that `win-config.exe` works well, closing.
