### ISSUE TITLE
Codepoint escape sequences are not always processed correctly

### ISSUE THREAD

**Issue by wouterbeek** [ClioPatria/ClioPatria#61]
According to the SPARQL standard, codepoint escape sequences must be processed prior to parsing the query string.  This means that even characters that belong to the SPARQL grammar can be escaped.

The current implementation only processed codepoint escape sequences at the level of atoms, e.g., variable names, with `uchar//1`.

This is fairly straightforward to implement correctly, by running to the codelist prior to parsing and removing/changing current uses of `uchar//1`.

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with 6a08c84c59b3b4b899253eb92cb7261b13a842e6.  Rather strange as the implementation was mostly a literal translation of the grammar ...  Maybe this was different in SPARQL 1.0 and I missed it.
