### ISSUE TITLE
HTTP Server times out on browse/list_graph

### ISSUE THREAD

**Issue by wmelder** [ClioPatria/ClioPatria#63]
When navigating the server from Places-> Graphs-> Click on a graph under "named graphs in RDF store", the server is sending /browse/list_graph?graph=<named-graph-uri> to Cliopatria http server.
Monitoring the server that runs Cliopatria (docker from jrvosse), it turns out only 1 processor is used and is consumed for 100%. This is the case until the server returns with a time out message. There are 32 cores available though, so I wondered whether Cliopatria distributes the request on multiple cores or not. The graph is quite large with over 471M triples. There are no other graphs in the RDF store. Server memory looks good: usage 51%, limit of 188GB.

**Comment by jrvosse** [comment]
Hi Willem, thanks for reporting this issue. I recognize this limitation from my own large graphs. 

If you click on a graph in the list, Cliopatria will compute a summary page intended to be used to explore the graph in more detail. This is quite handy for graphs with unknown content, and you do not know what to query for in the sparql interface, for example. It is using, as far as I know, a serial computation (so only 1 cpu) and quite expensive on large graphs. I assigned Jan to this issue but I do not think this will be sufficiently high on his priority list to fix this in the near future.

My own workarounds (since this occurs only with very large graphs, I do not encounter this frequently):

- change the server's time out limit to 0 seconds for no time out (not that dangereous if you are running cliopatria behind a firewall, login as admin and go to the settings menu in the browser)
- split up the graph in multiple smaller graphs
- make a small VoID file pointing to good, representative example resources in the large graph so you never need to click on the large graph to explore it. I used this for the talk of europe project, see https://linkedpolitics.project.cwi.nl/browse/list_triples?predicate=http%3A//rdfs.org/ns/void%23exampleResource.

Hope this helps

**Comment by wmelder** [comment]
Hi Jacco,

thanks for your suggestions. Indeed the browsing the graph gives a nice summary of the contents of the graph. I used it to monitor progress during load. But, as you say it is quite expensive on large graphs. Setting the timeout to 0 makes it run on 100% for more than one and a half hour (then I stopped it). 

Firing a comparable SPARQL query in yasgui also gives a error response (service unavailable):

`SELECT DISTINCT ?type (count(?type) as ?count)
WHERE {
  GRAPH <http://data.rdlabs.beeldengeluid.nl/lod/>
  { [] a ?type. }
}
ORDER BY DESC(?count)`

Now given the fact that this also results in one processor doing all the work I can conclude that also the SPARQL query engine is doing serial processing? And that, how unfortunate it may be, I can not run certain queries for large graphs? I will consider how to cut up the graph in pieces, but I'm afraid that when I want to run a query on multiple graphs the timeout will still be there.

**Comment by JanWielemaker** [comment]
The entire infrastructure uses threads to answer multiple web queries concurently, but not for a single web query.   Surely it is possible to run some of the analysis that give the details for a single graph in parallel.   I doubt that will be good enough to provide full details on a 471M triples graph in a reasonable time.   I still think it is worthwhile to add but it won't solve your problem.

My SPARQL is a little rusty and I'm unsure whether this query expresses what you intend.   Anyway, the settings provide a different set of limits for solving SPARQL queries.   I'd estimate that the query can be executed in a sensible time.  If that is not the case it might be wrong or the translation to a Prolog query might be rather sub-optimal.   The corresponding Prolog query should be

```
?- order_by([desc(Count)], aggregate(count, S^rdf(S,rdf:type,Class), Count)).
```
If you have the SWISH plugin installed you can try that (or, if you have the Prolog console open you can try it there).

AFAIK, none or very few SPARQL endpoints will be able to compute this type of summary information over a graph of this size in a reasonable time.

**Comment by JanWielemaker** [comment]
P.s.  For the SPARQL query you have to disable (rdfs) inferencing as that will make it really slow.

**Comment by wmelder** [comment]
Hi Jan,

thanks for the clear response. 

> For the SPARQL query you have to disable (rdfs) inferencing as that will make it really slow.

Does that mean remove the value `rdfs` for `Default entailment rules applied` from 'settings-> cliopatria' ?


--

**Comment by JanWielemaker** [comment]
That is one option.  It sets the default entailment.  You can also specify it per query using e.g.,
`entailment=none`.  See https://cliopatria.swi-prolog.org/help/http (bottom of page).

Using `rdfs` is notably expensive for `rdf:type` as it has to do type inferencing based on domain and range.  `rdfslite` does the transitive closure of `rdf:type`, but not domain/range.  I think `rdf` gives every resource an `rdf:type` of `rdf:Resource` (not sure).  `none` does no inferencing at all.

**Comment by wmelder** [comment]
I see what you mean from the /sparql section:

Name | Type | Default | Description
-- | -- | -- | --
entailment | none\|​rdf\|​rdfslite\|​rdfs | rdf | Entailment used

**Comment by wmelder** [comment]
Nice! Having set `settings->sparql->Default entailment used for SPARQL queries` from `rdf` (default) to `none` and clicking on a graph immediately returns the 'summary information for graph'-page. Problem solved, for that part. When clicking the `\#referenced classes` from the 'summary information'- page again the server returns a timeout. So, the timeout now has moved to `/browse/list_classes?graph=<named_graph_uri>`. I notice now, that this issue is basically about list_classes (that's what you get with that sparql query), a count for all (instances of) classes.

**Comment by JanWielemaker** [comment]
I think this is the wrong conclusion.  These `/browse` queries do not use SPARQL.  They use Prolog queries directly.  Some results in the browse module are cached though and navigating away from the page doesn't cause the old computation that will ultimately result in a cache entry to be created.  If you come back late enough for the computation to have finished you get the cached results.

`/browse/list_classes?graph=<named_graph_uri>` runs the equivalent of your SPARQL query except for the ordering in Prolog, which is still slow :cry: Given the representation is hard to do this concurrently ...

**Comment by wmelder** [comment]
>  If you come back late enough for the computation to have finished you get the cached results.
I see. So by that line of thought we can expect the `# referenced classes` request to finish after some time as well and a quick server response by that time.

**Comment by jrvosse** [comment]
On 5/1/19 1:36 PM, Willem Melder wrote:
> Hi Jacco,
> 
> thanks for your suggestions. Indeed the browsing the graph gives a nice summary of the contents of the graph. I used it to monitor progress during load.

Ah, I do not think this is a good idea, way too expensive on large graphs, which is the only case you really want to monitor progress.  So this just indicates we need some load progress indicator. How to do that depends a bit on how you upload the data (e.g. using the http browser interface, some other http api, directly on the SWI-Prolog prompt, etc.)

Not sure if Jan has any ideas around this... ?

Jacco
