### ISSUE TITLE
How to stop the daemon from listening on port 80

### ISSUE THREAD

**Issue by berezovskyi** [ClioPatria/ClioPatria#67]
When I try to start the server using `daemon.pl`, the engine always seems to attempt to listen on port 80 before anything else:

```
% [00:45:22.252100] [main] 2022-02-17 00:45:22.252 Initialized endpoint http://:80/messages
% [00:45:22.802096] [main] 2022-02-17 00:45:22.802 Initialized endpoint http://localhost:3020/cc
```

Tried commands:

```
./daemon.pl --port=3020 --ip=localhost --fork=false --sighup=quit
./daemon.pl --host=localhost:3020 --fork=false --sighup=quit
```

When I start the server via `run.pl`, the server only tries to listen on `localhost:3020` as expected. Is there any way to prevent binding to port 80 when running as a daemon? Thank you in advance!

**Comment by JanWielemaker** [comment]
I'm not entirely sure.   If you start using `daemon.pl` you can run `./daemon.pl --help` for the options.   The daemon library takes care of creating the HTTP server, possibly first doing work that needs to be done as root such as opening reserved ports.  The normal way to run it is typically e.g., `./daemon.pl --port=3020`.   When running under systemd you typically want to add `--no-fork` and if you want to restrict access to localhost add `--ip=localhost`.   There are lots of options, including starting as HTTPS server.

**Comment by berezovskyi** [comment]
Thank you both, Jacco and Jan!
